<?php

namespace Drupal\famtastic_pipeline\Service;

/** Generated by scripts/sync-creator-credit-php.mjs; do not hand-edit. */
final class CreatorCredit {
  public static function html(): string {
    return <<<'CREDIT'
<style>[data-famtastic-creator-credit] a:focus-visible{outline:3px solid #7cfc00;outline-offset:4px}@media(max-width:900px){body:has(.mobile-owner-nav) [data-famtastic-creator-credit],body:has(.portal-mobile-nav) [data-famtastic-creator-credit]{padding-bottom:calc(96px + env(safe-area-inset-bottom))!important}}@media(max-width:600px){body:has(.mobile-owner-nav) [data-famtastic-creator-credit],body:has(.portal-mobile-nav) [data-famtastic-creator-credit]{padding-bottom:calc(192px + env(safe-area-inset-bottom))!important}}</style><div data-famtastic-creator-credit="v1" style="display:flex;justify-content:center;width:100%;box-sizing:border-box;padding:12px;clear:both"><a href="https://famtasticdesigns.com/?utm_source=famtastic-designs&amp;utm_medium=creator_credit&amp;utm_campaign=created_by_famtastic" aria-label="Created by FAMtastic Designs" referrerpolicy="no-referrer" style="display:inline-flex;align-items:center;justify-content:center;min-height:44px;max-width:100%;padding:12px;background:#070907;border-radius:6px;box-sizing:border-box"><img src="https://famtasticdesigns.com/brand/famtastic-designs-logo-v1.png" alt="Created by FAMtastic Designs" width="2172" height="724" style="display:block;width:180px;max-width:100%;height:auto;object-fit:contain;filter:none;border:0"></a></div>
CREDIT;
  }
}
