import {execFileSync} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
const run=(args,cwd=process.cwd())=>execFileSync(args[0],args.slice(1),{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const repo=run(['git','rev-parse','--show-toplevel']);
if(run(['git','status','--porcelain'],repo))throw Error('clean_worktree_required');
run(['git','fetch','origin'],repo);
const commit=run(['git','rev-parse','HEAD'],repo);
if(run(['git','rev-parse','origin/main'],repo)!==commit)throw Error('exact_pushed_main_required');
const stage=mkdtempSync(join(tmpdir(),'locs-independent-release-'));
const archive=join(stage,'source.tar');
run(['git','archive','--format=tar','--output='+archive,commit,'customer-apps/tighten-up-your-locs/application','customer-apps/tighten-up-your-locs/gateway'],repo);
run(['tar','-xf',archive,'--strip-components=2','-C',stage]);
const app=join(stage,'application');
run(['composer','install','--no-dev','--no-interaction','--prefer-dist','--optimize-autoloader'],app);
run(['composer','audit','--no-dev','--format=plain'],app);
const bundle=join(stage,'locs-'+commit+'.tar.gz');
run(['tar','-czf',bundle,'-C',stage,'application','gateway']);
const sha=createHash('sha256').update(readFileSync(bundle)).digest('hex');
const receipt={commit,bundle,sha256:sha,source:'customer-apps/tighten-up-your-locs',status:'built_not_deployed'};
writeFileSync(join(stage,'build.json'),JSON.stringify(receipt,null,2),{flag:'wx',mode:0o600});
console.log(JSON.stringify(receipt));
