import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
const oldHost='xrdj7j99xhzt@p3plzcpnl497512.prod.phx3.secureserver.net';
const newHost='nineoo@p3plzcpnl506112.prod.phx3.secureserver.net';
const source=execFileSync('ssh',['-o','BatchMode=yes','-o','StrictHostKeyChecking=yes',oldHost,'cd /home/xrdj7j99xhzt/public_html && LOCS_MIGRATION_MODE=export-frozen-locs vendor/bin/drush php:script /home/xrdj7j99xhzt/deploy/famtastic-designs/locs-independent-legacy-export.php'],{maxBuffer:1048576,stdio:['ignore','pipe','pipe']});
const data=JSON.parse(source.toString('utf8'));
if(data.schema!=='locs.request-migration.v1'||data.site_key!=='site-dffd4cb9c3aa47fd'||data.retirement?.guards_verified!==12||data.records?.length!==1)throw Error('guarded_export_invalid');
const digest=createHash('sha256').update(source).digest('hex');
const dir=mkdtempSync('/private/tmp/locs-private-transfer-');const file=join(dir,'legacy-'+digest+'.json');
writeFileSync(file,source,{flag:'wx',mode:0o600});
const remote='/home/nineoo/customer-sites/tighten-up-your-locs/private/owner-app/legacy-'+digest+'.json';
execFileSync('scp',['-p',file,newHost+':'+remote],{stdio:['ignore','pipe','pipe']});
const verified=execFileSync('ssh',[newHost,"php -r 'if((fileperms(\""+remote+"\")&0777)!==0600)exit(1);echo hash_file(\"sha256\",\""+remote+"\");'"],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
if(verified!==digest)throw Error('remote_export_hash_mismatch');
console.log(JSON.stringify({status:'private_export_transferred',records:1,sha256:digest,local_private_file:file,remote_private_file:remote,notifications:0}));
