(() => {
 'use strict';
 const pages=['home','repair','maintenance','assessment','about','contact'];
 const form=document.querySelector('#request-form'), full=document.querySelector('#full-fields');
 let branch='callback';
 function showPage(focus=false){const route=location.hash.slice(1)||'home';if(route==='owner')return;const selected=pages.includes(route)?route:'home';document.querySelectorAll('[data-page]').forEach(el=>{el.hidden=el.dataset.page!==selected;});document.querySelectorAll('.masthead nav a').forEach(a=>{if(a.getAttribute('href')==='#'+selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(focus){const h=document.querySelector('[data-page="'+selected+'"] h1');h.setAttribute('tabindex','-1');h.focus();h.scrollIntoView({block:'start'});}}
 addEventListener('hashchange',()=>showPage(true));showPage();
 document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{form.elements.service.value=a.dataset.service;}));
 document.querySelectorAll('[data-branch]').forEach(button=>button.addEventListener('click',()=>{branch=button.dataset.branch;full.hidden=branch!=='full';full.disabled=branch!=='full';document.querySelectorAll('[data-branch]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#request-result').hidden=true;}));
 form.addEventListener('submit',event=>{event.preventDefault();const error=document.querySelector('#form-error');error.hidden=true;form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));const email=form.elements.email;email.required=branch==='full'&&form.elements.method.value==='Email';const invalid=Array.from(form.elements).find(el=>el.willValidate&&!el.checkValidity());if(invalid){error.textContent='Please check '+invalid.closest('label').childNodes[0].textContent.trim()+'. Your practice details are still here.';error.hidden=false;invalid.setAttribute('aria-invalid','true');invalid.focus();return;}const data=new FormData(form);const keys=branch==='full'?['name','phone','area','service','issue','method','email','address','unit','access','approver','payer','updates','timing','notes']:['name','phone','area','service','issue'];document.querySelector('#inquiry-summary').textContent='Fictional '+(branch==='full'?'full request':'callback request')+'\n'+keys.map(key=>key+': '+(data.get(key)||'Not supplied')).join('\n');document.querySelector('#request-result').hidden=false;});
 document.querySelector('#clear-request').addEventListener('click',()=>{form.reset();document.querySelector('#request-result').hidden=true;document.querySelector('#form-error').hidden=true;form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));document.querySelector('#inquiry-summary').textContent='Practice details cleared. No request was sent.';});
 document.querySelector('#reply-form').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#reply-notice').textContent='Practice draft saved in this page. Nothing sent: '+document.querySelector('#reply').value;document.querySelector('#request-status').selectedIndex=2;});
 document.querySelector('#reset-practice').addEventListener('click',()=>{document.querySelector('#reply-form').reset();document.querySelector('#request-status').selectedIndex=0;document.querySelector('#reply-notice').textContent='Owner practice reset.';document.querySelector('#inquiry-summary').textContent='Fictional example: cooling feels uneven. Service area and approval contact need clarification.';});
})();
