import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router';
import BrandLogo from '../components/BrandLogo.jsx';
import {getAcquisitionReport} from '../api/acquisition.js';
import '../acquisition.css';
const METRICS=[['eligible_recipients','Eligible recipients'],['sends','Sends'],['recorded_opens','Recorded opens'],['recorded_clicks','Recorded clicks'],['replies','Replies'],['verified_registrations','Verified registrations'],['completed_interviews','Completed interviews'],['paid_customers','Paid customers'],['refunds','Refunds'],['revenue_minor','Revenue'],['measured_cost_minor','Measured costs'],['contribution_minor','Contribution']];
function value(key,amount,currency){if(amount==null)return 'Unknown';return key.endsWith('_minor')?new Intl.NumberFormat('en-US',{style:'currency',currency:currency||'USD'}).format(amount/100):String(amount);}
export default function AcquisitionReportPage(){
 const {campaignKey='acquisition-199'}=useParams();
 const [report,setReport]=useState(null),[error,setError]=useState(''),[group,setGroup]=useState('niche');
 useEffect(()=>{const controller=new AbortController();setReport(null);setError('');getAcquisitionReport(campaignKey,controller.signal).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[campaignKey]);
 return <main className="acquisition-page"><header className="acquisition-header"><Link to="/" aria-label="FAMtastic Designs home"><BrandLogo/></Link><span>Private campaign scorecard</span></header><h1>From invitation to paid customer</h1><p>Current campaign records. Recorded opens and clicks can include scanners and privacy proxies; they do not prove human interest.</p>{error?<p role="alert">{error} Staff access is required.</p>:!report?<p role="status">Reading campaign records…</p>:<><div className="acquisition-report-scroll"><table className="acquisition-report-table"><caption>{report.campaign_key}</caption><thead><tr><th scope="col">Measure</th><th scope="col">Recorded total</th></tr></thead><tbody>{METRICS.map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{value(key,report.totals?.[key],report.currency)}</td></tr>)}</tbody></table></div><p>Meaningful sample preferences: {value('',report.interaction_quality?.meaningful_preferences)} · Verified claims: {value('',report.interaction_quality?.verified_claims)}</p><div className="acquisition-report-controls"><label htmlFor="report-group">Break down by </label><select id="report-group" value={group} onChange={e=>setGroup(e.target.value)}><option value="niche">Niche</option><option value="message">Message</option><option value="sample">Sample</option><option value="experiment_arm">Sample experiment</option></select></div><div className="acquisition-report-scroll"><table className="acquisition-report-table"><caption>Breakdown · {group.replace('_',' ')}</caption><thead><tr><th scope="col">Group</th><th scope="col">Sends</th><th scope="col">Paid customers</th><th scope="col">Revenue</th></tr></thead><tbody>{(report.breakdowns?.[group]||[]).map(row=><tr key={row.key}><th scope="row">{row.key}</th><td>{value('',row.totals?.sends)}</td><td>{value('',row.totals?.paid_customers)}</td><td>{value('revenue_minor',row.totals?.revenue_minor,report.currency)}</td></tr>)}</tbody></table></div>{!(report.breakdowns?.[group]||[]).length&&<p>No attributed records for this breakdown.</p>}<section aria-label="Controlled test outcomes"><h2>Controlled test records</h2><p>These records are excluded from campaign totals: {value('',report.controlled_sandbox?.messaging?.sends)} synthetic sends · {value('',report.controlled_sandbox?.paid_customers)} test paid customers · {value('revenue_minor',report.controlled_sandbox?.revenue_minor,report.currency)} test revenue.</p></section><h2>What still needs proof</h2><ul>{(report.gaps||[]).map(gap=><li key={gap}>{gap}</li>)}</ul><p>150 recipients is an operational discovery cohort. Compare assigned groups with counts and uncertainty; this table does not declare a statistical winner.</p></>}</main>;
}
