import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { createCustomerReferral, createCustomerThread, customerLogout, customerSession, getCustomerThread, getCustomerWorkspace, replyCustomerThread, updateCustomerPreferences, updateCustomerProfile } from '../api/customer.js';
import '../portal.css';

const GROUPS = [
  ['Overview', [['home', 'Home'], ['activity', 'Activity']]],
  ['My business', [['services', 'My services'], ['performance', 'Performance']]],
  ['Work with FAMtastic', [['projects', 'Projects & approvals'], ['messages', 'Messages'], ['support', 'Support']]],
  ['Learn & discover', [['learn', 'For you & latest'], ['faq', 'FAQs']]],
  ['Grow', [['grow', 'Recommended next steps'], ['referrals', 'Refer a friend']]],
  ['Account', [['billing', 'Purchases & billing'], ['account', 'Profile & team'], ['settings', 'Settings']]],
];
const LABELS = Object.fromEntries(GROUPS.flatMap(([, items]) => items));
const title = (value) => String(value || 'Preparing').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const money = (amount = 0, currency = 'usd') => new Intl.NumberFormat('en-US', { style: 'currency', currency: currency.toUpperCase() }).format(amount / 100);
const date = (stamp) => stamp ? new Date(Number(stamp) * 1000).toLocaleDateString() : 'Not scheduled';

function Panel({ eyebrow, title: heading, children, className = '' }) { return <article className={`portal-panel ${className}`}><span>{eyebrow}</span>{heading && <h2>{heading}</h2>}{children}</article>; }
function Empty({ children }) { return <p className="portal-empty">{children}</p>; }

export default function CustomerPortalDashboard() {
  const navigate = useNavigate();
  const [section, setSection] = useState('home');
  const [session, setSession] = useState(null);
  const [workspace, setWorkspace] = useState(null);
  const [state, setState] = useState('loading');
  const [menu, setMenu] = useState(false);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [activeThread, setActiveThread] = useState(null);
  const [faqSearch, setFaqSearch] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([customerSession(), getCustomerWorkspace()]).then(([s, w]) => { setSession(s); setWorkspace(w); setState('ready'); }).catch(() => navigate('/login', { replace: true })); }, [navigate]);
  const org = workspace?.organization;
  const project = workspace?.projects?.[0];
  const order = workspace?.orders?.[0];
  const owned = new Set(workspace?.entitlements?.map((item) => item.entitlement_type) || []);
  const nextAction = useMemo(() => !order ? 'Tell us what your business needs next' : order.payment_status !== 'paid' ? 'Complete your purchase' : !project ? 'Complete your project brief' : project.approval_status !== 'approved' ? 'Review and approve your project' : 'See your next growth opportunity', [order, project]);
  const filteredFaqs = useMemo(() => (workspace?.faqs || []).filter((item) => `${item.question} ${item.answer} ${item.category}`.toLowerCase().includes(faqSearch.toLowerCase())), [workspace, faqSearch]);
  if (state === 'loading') return <div className="portal-state"><i />Opening your customer command center…</div>;
  const go = (id) => { setSection(id); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const refresh = async () => setWorkspace(await getCustomerWorkspace(org.public_id));
  const act = async (work, success) => { setError(''); setBusy(true); try { await work(); if (success) setNotice(success); } catch (exception) { setError(exception.message); } finally { setBusy(false); } };
  const saveProfile = (event) => { event.preventDefault(); const form = event.currentTarget; act(async () => setSession(await updateCustomerProfile(Object.fromEntries(new FormData(form)))), 'Profile updated.'); };
  const saveSettings = (event) => { event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); data.topics = new FormData(form).getAll('topics'); act(async () => { const result = await updateCustomerPreferences(data); setWorkspace((current) => ({ ...current, preferences: result.preferences })); setSession((current) => ({ ...current, customer: { ...current.customer, marketing_status: result.preferences.deals_promotions ? 'subscribed' : 'unsubscribed' } })); }, 'Communication preferences saved.'); };
  const openThread = (event) => { event.preventDefault(); const form = event.currentTarget; act(async () => { await createCustomerThread({ ...Object.fromEntries(new FormData(form)), organization: org.public_id }); await refresh(); form.reset(); }, 'Your request was sent.'); };
  const viewThread = (id) => act(async () => setActiveThread(await getCustomerThread(id)));
  const replyThread = (event) => { event.preventDefault(); const form = event.currentTarget; act(async () => { await replyCustomerThread(activeThread.thread.public_id, new FormData(form).get('body')); setActiveThread(await getCustomerThread(activeThread.thread.public_id)); form.reset(); }, 'Reply sent.'); };
  const refer = (event) => { event.preventDefault(); const form = event.currentTarget; act(async () => { await createCustomerReferral({ ...Object.fromEntries(new FormData(form)), organization: org.public_id }); await refresh(); form.reset(); }, 'Referral recorded. Thank you for sharing FAMtastic.'); };

  return <div className={`portal-app ${menu ? 'menu-open' : ''}`}>
    <button className="portal-menu-toggle" type="button" aria-expanded={menu} aria-controls="portal-drawer" onClick={() => setMenu(!menu)}><span aria-hidden="true">☰</span><span>Menu</span></button>
    {menu && <button className="portal-scrim" aria-label="Close menu" onClick={() => setMenu(false)} />}
    <aside id="portal-drawer" className="portal-nav">
      <div className="portal-nav-head"><Link className="portal-logo" to="/">FAM<span>tastic</span></Link><button type="button" aria-label="Close menu" onClick={() => setMenu(false)}>×</button></div>
      <div className="portal-workspace"><small>Customer workspace</small><strong>{org?.name}</strong><em>{org?.role}</em></div>
      <nav aria-label="Customer portal">{GROUPS.map(([group, items]) => <section key={group}><h2>{group}</h2>{items.map(([id, label]) => <button key={id} aria-current={section === id ? 'page' : undefined} className={section === id ? 'active' : ''} onClick={() => go(id)}>{label}{id === 'messages' && workspace.threads.filter((t) => t.status === 'open').length > 0 && <b>{workspace.threads.filter((t) => t.status === 'open').length}</b>}</button>)}</section>)}</nav>
      <button className="portal-signout" onClick={() => act(async () => { await customerLogout(); navigate('/login'); })}>Sign out</button>
    </aside>
    <main className="portal-main">
      <header><div><span>FAMtastic customer portal</span><h1>{LABELS[section]}</h1></div><div className="portal-user"><i>{session.customer.display_name.slice(0, 1).toUpperCase()}</i><span>{session.customer.display_name}<small>{session.customer.email}</small></span></div></header>
      {notice && <div className="portal-notice" role="status">{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}>×</button></div>}
      {error && <div className="portal-notice portal-notice--error" role="alert">{error}<button aria-label="Dismiss" onClick={() => setError('')}>×</button></div>}

      {section === 'home' && <><section className="portal-welcome"><div><span>Welcome back</span><h2>{org?.name}</h2><p>Your digital business, active work, support, and next opportunities—together in one place.</p></div><div><small>Needs your attention</small><strong>{nextAction}</strong><button onClick={() => go(!order ? 'grow' : 'projects')}>Take the next step →</button></div></section><section className="portal-grid three"><Panel eyebrow="Website & services" title={`${workspace.entitlements.length} active`}><p>See what you own, coverage, renewals, and help for each service.</p><button onClick={() => go('services')}>View services</button></Panel><Panel eyebrow="Support" title={`${workspace.threads.filter((t) => t.status === 'open').length} open`}><p>Get help without repeating your account or project history.</p><button onClick={() => go('support')}>Get help</button></Panel><Panel eyebrow="Learn" title={`${workspace.articles.length} latest articles`}><p>Practical guidance selected around the capabilities you own and can benefit from.</p><button onClick={() => go('learn')}>Read and follow topics</button></Panel></section><section className="portal-grid two"><Panel eyebrow="Recent activity" title="What FAMtastic has handled">{workspace.activity.length ? <ul>{workspace.activity.slice(0, 5).map((item, i) => <li key={i}><strong>{item.summary}</strong><small>{date(item.created)}</small></li>)}</ul> : <Empty>Your account activity will appear here.</Empty>}</Panel><Panel eyebrow="Recommended for you" title={workspace.offers[0]?.title || 'You’re all set'} className="lime"><p>{workspace.offers[0]?.description || 'We will recommend a next step only when it fits your business.'}</p><button onClick={() => go('grow')}>Why this matters →</button></Panel></section></>}

      {section === 'activity' && <Panel eyebrow="Your history" title="Work, milestones, and account events">{workspace.activity.length ? <ul>{workspace.activity.map((item, i) => <li key={i}><strong>{item.summary}</strong><small>{date(item.created)}</small></li>)}</ul> : <Empty>No activity yet.</Empty>}</Panel>}
      {section === 'services' && <section className="portal-grid three">{workspace.entitlements.length ? workspace.entitlements.map((service) => <Panel key={service.public_id} eyebrow="Owned service" title={title(service.entitlement_type)}><p><strong>{title(service.status)}</strong></p><small>{service.included_until ? `Included through ${date(service.included_until)}` : 'Active on your account'}</small><button onClick={() => go('support')}>Get service help</button></Panel>) : <Panel eyebrow="Your services" title="Ready when you are"><p>Your active website, AI, automation, hosting, and analytics capabilities will appear here after purchase.</p><button onClick={() => go('grow')}>Explore what helps next</button></Panel>}</section>}
      {section === 'performance' && <section className="portal-grid two"><Panel eyebrow="Growth analytics" title={workspace.analytics.entitled ? 'Your performance dashboard' : 'Performance preview'} className="lime"><p>{workspace.analytics.entitled ? 'Visits, leads, and conversion insights are active for this workspace.' : 'Connect visits to leads and receive plain-language next actions.'}</p><a href="https://analytics.google.com/" target="_blank" rel="noreferrer">Open Google Analytics ↗</a></Panel><Panel eyebrow="Coming into focus" title="Business outcomes"><p>Lead capture, search visibility, website health, reviews, and AI-agent outcomes will consolidate here as each capability is connected.</p></Panel></section>}
      {section === 'projects' && <section className="portal-grid">{workspace.projects.length ? workspace.projects.map((p) => <Panel key={p.uuid} eyebrow="Website project" title={title(p.delivery_status)}><dl><div><dt>Approval</dt><dd>{title(p.approval_status)}</dd></div><div><dt>Revisions</dt><dd>{p.revision_count || 0} of {p.revision_limit || 1}</dd></div></dl>{p.proof_url && <a href={p.proof_url}>Review proof ↗</a>}{p.live_url && <a href={p.live_url}>Visit live site ↗</a>}</Panel>) : <Panel eyebrow="Projects" title="No active projects"><p>Purchased projects and approval actions will appear automatically.</p></Panel>}</section>}
      {section === 'messages' && <section className="portal-grid two"><Panel eyebrow="Conversations" title="Your history">{workspace.threads.length ? <ul className="portal-thread-list">{workspace.threads.map((thread) => <li key={thread.public_id}><button type="button" onClick={() => viewThread(thread.public_id)}><strong>{thread.subject}</strong><small>{title(thread.status)} · {date(thread.changed)}</small></button></li>)}</ul> : <Empty>No conversations yet.</Empty>}</Panel>{activeThread ? <Panel eyebrow={title(activeThread.thread.kind)} title={activeThread.thread.subject} className="portal-conversation"><button className="portal-back" onClick={() => setActiveThread(null)}>← All conversations</button><ol>{activeThread.messages.map((message, i) => <li key={i} className={`is-${message.author_type}`}><span>{message.author_type === 'customer' ? 'You' : 'FAMtastic team'}</span><p>{message.body}</p><small>{date(message.created)}</small></li>)}</ol><form onSubmit={replyThread}><label htmlFor="thread-reply">Reply</label><textarea id="thread-reply" name="body" required /><button disabled={busy}>{busy ? 'Sending…' : 'Send reply'}</button></form></Panel> : <Panel eyebrow="New conversation" title="Ask FAMtastic"><p>Choose the affected area so your request reaches us with the right context.</p><form onSubmit={openThread}><label>Area<select name="kind"><option value="support">Website or service issue</option><option value="project">Project or approval</option><option value="billing">Billing or renewal</option></select></label><label>Subject<input name="subject" required /></label><label>What happened?<textarea name="body" required /></label><button disabled={busy}>{busy ? 'Sending…' : 'Send request'}</button></form></Panel>}</section>}
      {section === 'support' && <><section className="portal-support-choices"><button onClick={() => go('messages')}><b>Website or service issue</b><span>Report something incorrect, unavailable, or broken.</span></button><button onClick={() => go('messages')}><b>Request a change</b><span>Update content, hours, services, or business information.</span></button><button onClick={() => go('faq')}><b>Find an answer</b><span>Search FAQs before waiting for a response.</span></button><a href="mailto:hello@famtasticdesigns.com?subject=Urgent%20customer%20support"><b>Urgent business impact</b><span>Email the team when your website, checkout, domain, or leads are unavailable.</span></a></section><Panel eyebrow="Support record" title={`${workspace.threads.filter((t) => t.status === 'open').length} open requests`}><p>Your requests and replies stay attached to your customer workspace.</p><button onClick={() => go('messages')}>View conversations</button></Panel></>}
      {section === 'learn' && <><Panel eyebrow="Personalize your feed" title="Follow topics that help your business"><p>Choose topics in Settings and control whether you receive educational email or only see them here.</p><button onClick={() => go('settings')}>Manage topic subscriptions</button></Panel><section className="portal-grid three portal-articles">{workspace.articles.length ? workspace.articles.map((article) => <Panel key={article.id} eyebrow={article.topic} title={article.title}><p>{article.excerpt || 'Read the latest practical guidance from FAMtastic Designs.'}</p><a href={article.url}>Read article →</a></Panel>) : <Panel eyebrow="Latest articles" title="New guidance is coming"><p>Published Drupal blog posts will appear here automatically.</p></Panel>}</section></>}
      {section === 'faq' && <><label className="portal-search" htmlFor="faq-search"><span>Search questions and answers</span><input id="faq-search" type="search" value={faqSearch} onChange={(event) => setFaqSearch(event.target.value)} placeholder="Try: domain, hosting, AI agent, billing…" /></label><section className="portal-faqs">{filteredFaqs.length ? filteredFaqs.map((faq) => <details key={faq.id}><summary>{faq.question}</summary><p>{faq.answer}</p><small>{faq.category}</small></details>) : <Panel eyebrow="No answer found" title="Ask FAMtastic"><p>Start a support request and we’ll keep the answer with your account.</p><button onClick={() => go('support')}>Get help</button></Panel>}</section></>}
      {section === 'grow' && <section className="portal-grid three">{workspace.offers.map((offer) => <Panel key={offer.key} eyebrow="Recommended next step" title={offer.title} className="offer"><p>{offer.description}</p><small>Recommended from your current services and project stage.</small><a href={`/contact?service=${offer.key}`}>Ask how this helps →</a></Panel>)}<Panel eyebrow="Not sure what you need?" title="Have FAMtastic handle it" className="lime"><p>Tell us the outcome you want. We’ll recommend the smallest useful next step.</p><button onClick={() => go('support')}>Describe my goal</button></Panel></section>}
      {section === 'referrals' && <section className="portal-grid two"><Panel eyebrow="Refer a friend" title="Help another business get online"><p>Share FAMtastic only with someone who has agreed to hear from us. We’ll track the introduction without displaying their private activity.</p><form onSubmit={refer}><label>Friend’s name<input name="friend_name" required /></label><label>Friend’s email<input name="friend_email" type="email" inputMode="email" required /></label><label className="portal-check"><input name="permission_confirmed" type="checkbox" value="1" required />They gave me permission to share their information.</label><button disabled={busy}>{busy ? 'Recording…' : 'Record referral'}</button></form><div className="portal-share"><a href="sms:?&body=FAMtastic%20Designs%20can%20help%20you%20get%20online:%20https://famtasticdesigns.com">Text a friend</a><a href="mailto:?subject=FAMtastic%20Designs&body=Take%20a%20look:%20https://famtasticdesigns.com">Email a friend</a></div></Panel><Panel eyebrow="Your referrals" title={`${workspace.referrals.length} shared`}>{workspace.referrals.length ? <ul>{workspace.referrals.map((referral) => <li key={referral.public_id}><strong>{referral.friend_name}</strong><small>{title(referral.status)} · {title(referral.reward_status)}</small></li>)}</ul> : <Empty>Your referral history and earned rewards will appear here.</Empty>}</Panel></section>}
      {section === 'billing' && <section className="portal-grid two">{workspace.orders.length ? workspace.orders.map((purchase) => <Panel key={purchase.uuid} eyebrow="Purchase" title={money(purchase.amount, purchase.currency)}><dl><div><dt>Package</dt><dd>{title(purchase.package)}</dd></div><div><dt>Payment</dt><dd>{title(purchase.payment_status)}</dd></div><div><dt>Date</dt><dd>{date(purchase.created)}</dd></div></dl></Panel>) : <Panel eyebrow="Purchases" title="No purchases yet"><p>Your orders, receipts, and renewal information will appear here.</p></Panel>}<Panel eyebrow="Payment security" title="Secure billing"><p>Payment methods are managed through Stripe. FAMtastic never stores card details in the portal.</p></Panel></section>}
      {section === 'account' && <section className="portal-grid two"><Panel eyebrow="Profile" title="Contact information"><form onSubmit={saveProfile}><label>Name<input name="display_name" defaultValue={session.customer.display_name} /></label><label>Phone<input name="phone" defaultValue={session.customer.phone} inputMode="tel" /></label><button disabled={busy}>{busy ? 'Saving…' : 'Save profile'}</button></form></Panel><Panel eyebrow="Workspace access" title="Team members"><ul>{workspace.members.map((member) => <li key={member.public_id}><strong>{member.display_name}</strong><small>{member.email} · {title(member.role)}</small></li>)}</ul></Panel></section>}
      {section === 'settings' && <Panel eyebrow="Settings" title="Notifications, education, and promotions"><form onSubmit={saveSettings} className="portal-settings"><fieldset><legend>Essential account messages</legend><label className="portal-check"><input type="checkbox" name="project_email" value="1" defaultChecked={workspace.preferences.project_email} />Project updates and approvals by email</label><label className="portal-check"><input type="checkbox" name="support_email" value="1" defaultChecked={workspace.preferences.support_email} />Support replies by email</label><label className="portal-check"><input type="checkbox" name="billing_email" value="1" defaultChecked={workspace.preferences.billing_email} />Billing and renewal notices by email</label><small>Critical security and account notices may still be sent when required to operate your services.</small></fieldset><fieldset><legend>Education and offers</legend><label className="portal-check"><input type="checkbox" name="product_education" value="1" defaultChecked={workspace.preferences.product_education} />Helpful product education</label><label className="portal-check"><input type="checkbox" name="deals_promotions" value="1" defaultChecked={workspace.preferences.deals_promotions} />Deals, promotions, and relevant service offers</label><label>Analytics summary<select name="analytics_digest" defaultValue={workspace.preferences.analytics_digest}><option value="off">Off</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label></fieldset><fieldset><legend>Topics I follow</legend><div className="portal-topic-grid">{Object.entries(workspace.topics).map(([key, label]) => <label className="portal-check" key={key}><input type="checkbox" name="topics" value={key} defaultChecked={workspace.preferences.topics.includes(key)} />{label}</label>)}</div></fieldset><button disabled={busy}>{busy ? 'Saving…' : 'Save settings'}</button></form></Panel>}
    </main>
  </div>;
}
