<?php
declare(strict_types=1);
use Drupal\famtastic_pipeline\Service\AcquisitionWindowSchedule;
// Dedicated CLI deployment; no dispatch, schema or broad provider/queue mutation.
$commit=(string)getenv('FAMTASTIC_BATCH50_SOURCE_COMMIT');$apply=getenv('FAMTASTIC_BATCH50_APPLY')==='1';
if(PHP_SAPI!=='cli'||!preg_match('/^[a-f0-9]{40}$/D',$commit))throw new RuntimeException('batch50_source_required');
$home='/home/xrdj7j99xhzt';$private=$home.'/private_files/acquisition-199';$release=$home.'/deploy/famtastic-designs/releases/'.$commit.'/batch50-source';$relative='/backend/web/modules/custom/famtastic_pipeline/src/Service/AcquisitionWindowExecutor.php';$target=$home.'/public_html/web/modules/custom/famtastic_pipeline/src/Service/AcquisitionWindowExecutor.php';$source=$release.$relative;
if(trim((string)file_get_contents($release.'/commit.txt'))!==$commit||realpath(__FILE__)!==$release.'/scripts/acquisition-batch50-promote.php'||realpath($source)!==$source||is_link($source)||is_link($target))throw new RuntimeException('batch50_exact_source_required');
if(!hash_equals(hash_file('sha256',$release.'/executor-baseline.php'),hash_file('sha256',$target)))throw new RuntimeException('batch50_deployed_baseline_changed');
$local=new DateTimeImmutable('now',new DateTimeZone('America/New_York'));
if($apply&&(int)$local->format('G')>=9&&(int)$local->format('G')<=12&&(int)$local->format('i')<5)throw new RuntimeException('batch50_apply_outside_normal_hours_required');
$readCron=static function():string{$lines=[];$code=0;exec('crontab -l 2>/dev/null',$lines,$code);if($code)throw new RuntimeException('batch50_cron_unreadable');return implode("\n",$lines)."\n";};
$writePrivate=static function(string $path,string $bytes):void{$mask=umask(0077);try{$f=fopen($path,'x');if(!$f)throw new RuntimeException('batch50_immutable_backup_exists');fwrite($f,$bytes);fclose($f);chmod($path,0600);}finally{umask($mask);}};
$installPath=$private.'/industry-clock-install-receipt.json';$installBytes=file_get_contents($installPath);$install=json_decode($installBytes,true,64,JSON_THROW_ON_ERROR);$oldInput=$install['routine_input'];$signed=json_decode(file_get_contents($oldInput),true,64,JSON_THROW_ON_ERROR);$config=$signed['config'];$key=trim(file_get_contents($private.'/owner-signing.key'));
if(strlen($key)<32||!hash_equals(hash_hmac('sha256',json_encode($config,JSON_THROW_ON_ERROR),$key),$signed['signature']))throw new RuntimeException('batch50_signature_changed');
if(($config['day_cap']??0)!==200||($config['window_cap']??0)!==50||($config['hours']??[])!==[9,10,11,12]||($config['transactional_unobserved_day_reserve']??0)!==250||($config['transactional_unobserved_hour_reserve']??0)!==400||($config['campaign_id']??0)!==5||isset($config['today_exception'])||isset($config['batch_size'])||($config['execution_mode']??'scheduled')!=='scheduled'||($config['starts_on']??'')!=='2026-10-07'||($config['ends_on']??'')!=='2026-10-16')throw new RuntimeException('batch50_existing_approved_schedule_required');
foreach(['frontend','backend'] as $kind){$marker=file_get_contents($home.'/public_html/.'.$kind.'-release');if(!str_contains($marker,'commit='.$config['binding_config'][$kind.'_sha']."\n"))throw new RuntimeException('batch50_production_release_changed');}
if(!hash_equals($config['queue_sha256'],hash_file('sha256',$config['queue_path'])))throw new RuntimeException('batch50_queue_changed');
$cron=$readCron();if(!AcquisitionWindowSchedule::inspect($cron,$home,$oldInput))throw new RuntimeException('batch50_installed_owned_clock_required');
$db=\Drupal::database();$quota=\Drupal::service('famtastic_pipeline.acquisition_window_quota');
if($quota->clockStatus()!=='active'||(int)$db->select('famtastic_acquisition_window','w')->condition('status','running')->countQuery()->execute()->fetchField()||(int)$db->select('famtastic_acquisition_dispatch','d')->condition('status',['reserved','uncertain'],'IN')->countQuery()->execute()->fetchField())throw new RuntimeException('batch50_no_active_or_uncertain_run_required');
$fingerprint=static function()use($db):string{$digest=hash_init('sha256');foreach(['famtastic_acquisition_window','famtastic_acquisition_slot','famtastic_acquisition_message'] as $table){$q=$db->select($table,'t');if($table==='famtastic_acquisition_message'){$q->fields('t',['message_id','invitation_id','day','content_id','content_hash','draft_hash']);$q->addExpression('SHA2(snapshot,256)','snapshot_sha256');$q->orderBy('message_id');}else{$q->fields('t');$q->orderBy($table==='famtastic_acquisition_window'?'window_key':'slot_key');}foreach($q->execute() as $row)hash_update($digest,json_encode((array)$row,JSON_THROW_ON_ERROR));}return hash_final($digest);};
$beforeFingerprint=$fingerprint();$count=(int)$db->select('famtastic_email_message','m')->condition('campaign_id',5)->condition('sent_at',0,'>')->condition('provider','smtp')->countQuery()->execute()->fetchField();
$out=['checked_at'=>gmdate(DATE_ATOM),'status'=>'preflight_checked','candidate_source_commit'=>$commit,'base_backend_commit'=>$config['binding_config']['backend_sha'],'frontend_commit'=>$config['binding_config']['frontend_sha'],'scope'=>'one_executor_file_and_signed_normal_config','required_batch_size'=>50,'day_cap'=>200,'hour_window_cap'=>50,'hours_eastern'=>[9,10,11,12],'accepted_before'=>$count,'messages_sent_by_deployment'=>0];
if(!$apply){echo json_encode($out,JSON_THROW_ON_ERROR)."\n";return;}
$newInput=$private.'/windows-batch50-'.substr($commit,0,8).'.json';$backup=$private.'/batch50-'.substr($commit,0,8);$paused=AcquisitionWindowSchedule::remove($cron,$home,$oldInput);$next=AcquisitionWindowSchedule::install($paused,$home,$newInput);
$newConfig=$config;$newConfig['batch_size']=50;$newConfig['batch_executor_sha256']=hash_file('sha256',$source);$newConfig['batch_executor_source_commit']=$commit;
$writePrivate($backup.'.cron-before',$cron);$writePrivate($backup.'.cron-paused',$paused);$writePrivate($backup.'.cron-next',$next);$writePrivate($backup.'.executor-before',file_get_contents($target));$writePrivate($backup.'.install-before',$installBytes);
$writePrivate($newInput,json_encode(['config'=>$newConfig,'signature'=>hash_hmac('sha256',json_encode($newConfig,JSON_THROW_ON_ERROR),$key)],JSON_THROW_ON_ERROR));
$installCron=static function(string $file,string $expected)use($readCron):void{$out=[];$rc=0;exec('crontab '.escapeshellarg($file),$out,$rc);if($rc||$readCron()!==$expected)throw new RuntimeException('batch50_cron_install_failed');};
$pausedInstalled=false;$promoted=false;
try{
 if($readCron()!==$cron)throw new RuntimeException('batch50_concurrent_cron_change');$installCron($backup.'.cron-paused',$paused);$pausedInstalled=true;
 if(!hash_equals(hash_file('sha256',$release.'/executor-baseline.php'),hash_file('sha256',$target)))throw new RuntimeException('batch50_concurrent_source_change');
 $staged=$backup.'.executor-next';$writePrivate($staged,file_get_contents($source));if(!chmod($staged,0644)||!rename($staged,$target))throw new RuntimeException('batch50_promotion_failed');$promoted=true;if(!hash_equals(hash_file('sha256',$source),hash_file('sha256',$target)))throw new RuntimeException('batch50_promoted_bytes_changed');
 // A separate fresh process loads the promoted executor, never the deployment process's class cache.
 $lines=[];$rc=0;$command='cd '.escapeshellarg($home.'/public_html').' && /usr/local/bin/php vendor/bin/drush.php famtastic:acquisition-window --input='.escapeshellarg($newInput).' --check-config';exec($command,$lines,$rc);$check=null;foreach($lines as $line){$v=json_decode($line,true);if(is_array($v)&&isset($v['status']))$check=$v;}
 if($rc||($check['status']??'')!=='checked'||($check['required_batch_size']??0)!==50||($check['effective_shared_day_cap']??0)!==200||($check['sent']??-1)!==0)throw new RuntimeException('batch50_promoted_check_failed');
 if(!hash_equals($beforeFingerprint,$fingerprint()))throw new RuntimeException('batch50_native_record_drift');
 if($readCron()!==$paused)throw new RuntimeException('batch50_concurrent_cron_change');$installCron($backup.'.cron-next',$next);
 $install['routine_input']=$newInput;$install['batch_size']=50;$install['batch_executor_overlay_commit']=$commit;$install['batch_executor_sha256']=$newConfig['batch_executor_sha256'];$install['capacity_check']=$check;$install['batch50_checked_at']=gmdate(DATE_ATOM);
 $temporary=$backup.'.install-next';$writePrivate($temporary,json_encode($install,JSON_THROW_ON_ERROR));if(file_get_contents($installPath)!==$installBytes)throw new RuntimeException('batch50_concurrent_install_change');if(!rename($temporary,$installPath))throw new RuntimeException('batch50_install_receipt_failed');
 $out=array_replace($out,['status'=>'applied_readback','checked_at'=>gmdate(DATE_ATOM),'check_only_result'=>$check,'normal_timer_installed'=>AcquisitionWindowSchedule::inspect($readCron(),$home,$newInput),'all_window_slot_and_snapshot_fingerprints_unchanged'=>hash_equals($beforeFingerprint,$fingerprint()),'accepted_after'=>(int)$db->select('famtastic_email_message','m')->condition('campaign_id',5)->condition('sent_at',0,'>')->condition('provider','smtp')->countQuery()->execute()->fetchField(),'clock_latch_reset'=>false,'uncertain_or_accepted_retry'=>false,'other_cron_preserved'=>AcquisitionWindowSchedule::remove($readCron(),$home,$newInput)===$paused]);
 $writePrivate($private.'/batch50-release-'.substr($commit,0,8).'.json',json_encode($out,JSON_THROW_ON_ERROR));$marker=$home.'/public_html/.acquisition-batch-release.json';if(file_exists($marker))throw new RuntimeException('batch50_overlay_marker_exists');$writePrivate($marker,json_encode($out,JSON_THROW_ON_ERROR));echo json_encode($out,JSON_THROW_ON_ERROR)."\n";
}catch(Throwable $e){
 // Restore only owned state and only if nobody changed it in the meantime.
 $current=$readCron();if($pausedInstalled&&($current===$paused||$current===$next)){$installCron($backup.'.cron-paused',$paused);if($promoted&&hash_equals(hash_file('sha256',$source),hash_file('sha256',$target))){copy($backup.'.executor-before',$target);chmod($target,0644);}if(file_get_contents($installPath)===json_encode($install,JSON_THROW_ON_ERROR))file_put_contents($installPath,$installBytes);$installCron($backup.'.cron-before',$cron);}
 throw $e;
}
