<?php
declare(strict_types=1);
// New draft lane only. Approved beauty bytes are read and checked, never rendered
// or rewritten. This script never bootstraps Drupal or a sending provider.
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
$root=dirname(__DIR__);
$base=$root . '/marketing/campaigns/acquisition-199';
$out=$base . '/industry-d0-drafts';
require $root . '/backend/web/modules/custom/famtastic_pipeline/src/Service/BrandedEmail.php';
use Drupal\famtastic_pipeline\Service\BrandedEmail;
$read=static fn(string $p): array=>json_decode(file_get_contents($p),true,512,JSON_THROW_ON_ERROR);
$approval=$read($root . '/docs/research/acquisition-199/CREATIVE-APPROVAL.json');
$freeze=static function() use ($approval,$root): void { foreach($approval['artifact_sha256'] as $p=>$hash) if(!hash_equals($hash,hash_file('sha256',$root . '/' . $p))) throw new RuntimeException('Approved beauty artifact changed: ' . $p); };
$freeze();
$coverage=$read($base . '/reuse-coverage.json');
$terms=$read($base . '/messages.json')['messages'][0]['terms'];
$esc=static fn(string $s): string=>htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$definitions=[
  1=>['id'=>'mobile-auto','subject'=>'A clearer next step for your auto-service website','preview'=>'Service details, vehicle inquiries and a practical owner workflow from your phone — a focused website starting point.','headline'=>'The care is in the details.','intro'=>'Clear service details help a vehicle owner understand the offer and know what to ask before getting in touch.','phone'=>'For mobile detailing, auto care or tinting, picture a website that explains the relevant services and a phone workflow for reviewing vehicle and location details, preparing a reply and keeping the next step clear.','sample_scope'=>'Mobile detailing, auto care and tinting are different services. A matching example must choose and label its actual scope; a detailing sample does not prove repair or tinting capabilities.','preview_brief'=>'Vehicle-service photography appropriate to the selected detailing, auto-care or tinting subcategory; approved service details and location/request path.'],
  2=>['id'=>'fitness-meal-prep','subject'=>'Make the first step into your offer easier','preview'=>'Training or meal-prep inquiries, clear offer details and a phone owner workflow — designed around the work you actually do.','headline'=>'A clear start. A personal next step.','intro'=>'A useful website makes it easier to understand an offer and start the right conversation.','phone'=>'For fitness, personal training or meal prep, picture clear offer details and a phone workflow for reviewing an inquiry, preparing a reply and updating the instructions people need before taking the next step.','sample_scope'=>'Training and meal prep require different intake and service details. No health outcome, medical advice, class calendar, meal subscription or nutrition qualification is implied.','preview_brief'=>'Owned or cleared training/fitness imagery or a separate meal-prep scene, with an explicit subcategory label and verified service boundaries.'],
  3=>['id'=>'photography-media','subject'=>'Give your creative work a clearer front door','preview'=>'A place for your approved portfolio, useful project inquiries and a phone workflow for keeping the next conversation organized.','headline'=>'Let the work start the conversation.','intro'=>'Creative work deserves a clear place to be seen, with a useful next step for someone planning a project.','phone'=>'For photography, videography or media work, picture an approved portfolio and a phone workflow for reviewing a brief, preparing a reply and keeping the project inquiry organized.','sample_scope'=>'Only rights-cleared portfolio work may be shown. A project inquiry is not a confirmed booking, promised production date or included file-delivery platform.','preview_brief'=>'Agency-owned or permission-cleared photographic/media portfolio scene; project type, date and brief path without copied customer portfolio media.'],
  4=>['id'=>'baking-catering-chefs','subject'=>'Make the first occasion conversation easier','preview'=>'Date and gathering details, a clear offer and a practical phone workflow — without promising an unconfirmed occasion or menu.','headline'=>'The occasion begins with a conversation.','intro'=>'Before the first cake, menu or gathering takes shape, there is a conversation about the occasion.','phone'=>'For custom baking, catering or private-chef work, picture clear offer details and a phone workflow for reviewing the date and gathering needs, preparing a reply and keeping the next step together.','sample_scope'=>'Baking, catering and private-chef requirements differ. No date availability, allergy guarantee, menu, checkout or kitchen suitability is invented.','preview_brief'=>'Owned or cleared baking, catered table or private-chef craft imagery appropriate to one labeled example; date/guest-count/request path.'],
  5=>['id'=>'home-services','subject'=>'A clearer path from service details to job inquiry','preview'=>'Help people explain the work they need, then review the inquiry, prepare a reply and keep its status clear from your phone.','headline'=>'Clear details. A useful next step.','intro'=>'A customer should be able to understand the service and explain the job without guessing what information to send.','phone'=>'For home services, cleaning or maintenance, picture clear service boundaries and a phone workflow for reviewing the job and location details, preparing a reply and keeping the inquiry status visible.','sample_scope'=>'No trade licence, insurance, travel area, quote acceptance or visit availability is asserted. Cleaning and specialist maintenance need separately verified service details.','preview_brief'=>'Owned or cleared cleaning/maintenance craft scene matched to the actual service; location/job-detail inquiry without invented credentials.'],
  6=>['id'=>'events-entertainment','subject'=>'Make the next event inquiry easier to work with','preview'=>'Gather the event details that matter, prepare a reply and keep the next step clear from your phone — before anything is confirmed.','headline'=>'A memorable event starts with clear details.','intro'=>'An event starts with a date, a place and an idea worth bringing together.','phone'=>'For events, party rentals or entertainment, picture a website that explains the offer and a phone workflow for reviewing the occasion details, preparing a reply and keeping the request organized.','sample_scope'=>'An inquiry reserves no date, venue, performer or rental item. Inventory, deposits, ticketing and event calendars are separate scope.','preview_brief'=>'Owned or cleared event, rental or entertainment scene for one clearly labeled offer; event-date/location/request path.'],
  7=>['id'=>'pet-services','subject'=>'A clear first conversation for pet-service inquiries','preview'=>'Explain the service, collect the useful first questions and work the next reply from your phone, with your real policies in view.','headline'=>'Thoughtful care starts with a clear conversation.','intro'=>'People want to understand the service and ask the right questions before trusting someone with their pet.','phone'=>'For pet services, grooming or training, picture clear service information and a phone workflow for reviewing the inquiry, preparing a reply and keeping the next step and instructions together.','sample_scope'=>'No animal-care credential, vaccination policy, handling assurance, availability or training result is invented. Publish only actual owner-approved policies.','preview_brief'=>'Owned or cleared pet grooming/care/training imagery appropriate to one labeled service; species/service/inquiry path with actual policies.'],
  8=>['id'=>'consulting-tutoring-creators','subject'=>'Give your expertise a clear next conversation','preview'=>'Explain the offer, understand an inquiry and prepare the next reply from your phone — without adding an unnecessary platform.','headline'=>'Make the next conversation count.','intro'=>'A clear offer helps someone understand what you do and bring a useful question to the first conversation.','phone'=>'For consulting, tutoring or digital-creator work, picture clear offer details and a phone workflow for reviewing the goal or topic, preparing a reply and keeping the next step organized.','sample_scope'=>'No learning result, credential, consultation availability, course platform, subscription or digital-product checkout is implied.','preview_brief'=>'Owned or cleared consultation, tutoring or creator-work scene; one explicit offer and topic/goal inquiry without borrowed student/client media.'],
  9=>['id'=>'handcrafted-fashion-boutiques','subject'=>'Give the craft a clear place to be discovered','preview'=>'Tell the product story, make the next inquiry useful and keep replies organized from your phone — with commerce scoped separately.','headline'=>'Give the details room to tell their story.','intro'=>'The details behind a piece are part of what makes it worth discovering.','phone'=>'For handcrafted products, fashion or boutiques, picture a clear product story and a phone workflow for reviewing a product or custom-work inquiry, preparing a reply and keeping the next step together.','sample_scope'=>'No inventory, shipping, checkout, payment, returns or custom-order acceptance is implied by the starter website. Ecommerce receives separate scope.','preview_brief'=>'Owned or cleared product/craft/fashion imagery for one labeled example, with a rights-cleared catalog/story and inquiry path.'],
];
if(!is_dir($out)) mkdir($out,0755,true);
$card='https://famtasticdesigns.com/connect';
$commercial=$card . '/commercial.mp4';
$shared='../generic-review/assets/';
$drafts=[];
foreach($definitions as $index=>$d){
  $category=$coverage['categories'][$index]['label'];
  $href='preview-status.html#' . $d['id'];
  $intro='Hello,\n\n' . $d['intro'] . '\n\n' . $d['phone'];
  $m=['id'=>$d['id'] . '-d0-v1','version'=>1,'day'=>0,'status'=>'draft_not_owner_approved','industry_source_label'=>$category,'industry_source'=>'Supplied workbook segment, unverified; no business or recipient identity claimed','subject'=>$d['subject'],'preview'=>$d['preview'],'headline'=>$d['headline'],'greeting'=>'Hello,','intro'=>$d['intro'],'phone_proposition'=>$d['phone'],'cta_label'=>'See what your website could look like','cta_binding'=>'approved_industry_matching_invitation_url','review_cta'=>$href,'terms'=>$terms,'signature'=>'Shay-Shay','identity'=>'FAMtastic Designs assistant','matching_preview'=>['status'=>'missing_owned_industry_asset_and_unapproved_destination','image_path'=>null,'owner_approved'=>false,'brief'=>$d['preview_brief'],'scope_boundary'=>$d['sample_scope'],'beauty_fallback_allowed'=>false,'rejected_six_fallback_allowed'=>false],'review_layout'=>'Approved beauty D0 shape: existing BrandedEmail, early primary CTA, compact commercial, one scope disclosure, signature/card/QR; no beauty content copied','send_policy'=>['approved'=>false,'dispatch_connected'=>false,'requires'=>['matching industry preview and destination','exact owner content approval','native industry match binding','current provider permission and sender readiness','bound invitation and unsubscribe','exact recipient/batch authorization'],'exit_on'=>['human_reply','purchase','opt_out','complaint','hard_bounce']],'followups'=>['d3'=>'unapproved_not_generated','d7'=>'unapproved_not_generated']];
  $drafts[]=$m;
  $body='<p>Hello,</p><p>' . $esc($d['intro']) . '</p><p>' . $esc($d['phone']) . '</p><p style="margin:24px 0 8px;"><a class="primary-demo-cta" href="' . $href . '" style="display:inline-block;box-sizing:border-box;max-width:100%;min-height:52px;padding:16px 20px;border:1px solid #7cfc00;border-radius:999px;background:#7cfc00;color:#070907;text-decoration:none;font-size:13px;font-weight:800;line-height:20px;text-align:center;">See what your website could look like</a></p><p style="font-size:12px;margin:0 0 20px;"><a href="' . $commercial . '" style="color:#284500;display:inline-block;min-height:44px;padding:8px 0;">Watch the short commercial →</a></p><p>If the approach fits, start with an interview about the business and the way you work. The eligible focused starter is <strong>$199 upfront</strong>, including the first year of managed hosting.</p><p style="font-size:13px;line-height:1.6;">' . $esc($terms) . '</p><p style="font-size:12px;">The eventual sample is illustrative; connected workflow is agreed in scope. Practice edits send or publish nothing. This draft has no approved matching sample yet.</p><p><strong>Shay-Shay</strong><br>FAMtastic Designs assistant</p><p style="font-size:13px;"><a href="' . $card . '" style="color:#284500;display:inline-block;min-height:44px;padding:10px 0;">Digital card</a></p><img src="' . $shared . 'connect-qr.png" width="160" height="160" alt="Scan to open the FAMtastic Designs digital card" style="display:block;width:160px;height:160px;margin:12px 0;background:#fff;"><p style="font-size:12px;">If images are blocked, use the Digital card link above. If this is not useful, reply and we will stop. <a href="https://example.invalid/unsubscribe-not-bound" style="color:#284500;">Unsubscribe</a> (unbound draft placeholder)</p>';
  $steps='<section aria-label="Your next steps" style="margin:26px 0;font-size:14px;line-height:1.65;"><p><strong>Your next steps are simple:</strong></p><ol style="margin:8px 0;padding-left:22px;"><li>Create your free account and complete your website interview.</li><li>Review three design directions, choose your favorite and request any adjustments.</li><li>Review your staged website.</li><li>Pay $199 and approve launch—we connect your domain and get your website online.</li></ol><p><a data-registration-binding="native_sample_continuation_required" href="' . $href . '" style="color:#284500;display:inline-block;min-height:44px;padding:10px 0;">Create your free account →</a> <span style="font-size:11px;">(review: native invitation binding pending)</span></p><p style="font-size:13px;">We aim for same-day launch once your site is approved, payment is complete and the domain is ready.</p><p style="font-size:12px;">Domain and email setup options are agreed in scope. Mailbox subscriptions are separate.</p></section>';
  $body=str_replace('<p style="font-size:13px;line-height:1.6;">',$steps . '<p style="font-size:13px;line-height:1.6;">',$body);
  $html=BrandedEmail::render($d['subject'],$body,BrandedEmail::LOGO_URL,$d['headline'],'A FAMtastic possibility','https://example.invalid/invitation-not-bound','Review the matching preview status',$d['preview']);
  $html=str_replace(BrandedEmail::LOGO_URL,$shared . 'famtastic-designs-logo-v1.png',$html);
  $html=str_replace('https://example.invalid/invitation-not-bound',$href,$html);
  $html=str_replace('>example.invalid</p>','>Draft preview status</p>',$html);
  $banner='<div role="note" style="padding:12px;background:#fff4c2;color:#302400;font:12px/1.5 Arial;">DRAFT ONLY · ' . $esc($category) . '. Copy for owner review; matching imagery and destination are still missing/unapproved. This CTA opens the preview-status page, not a finished industry demo. Sending held.</div>';
  $html=preg_replace('/(<body[^>]*>)/','$1' . $banner,$html,1);
  file_put_contents($out . '/' . $d['id'] . '.html',$html);
  file_put_contents($out . '/' . $d['id'] . '-images-blocked.html',preg_replace('/<img\b[^>]*>/','<span style="font-size:12px;">[Image blocked in this review]</span>',$html));
  $text='Subject: ' . $d['subject'] . "\nPreview: " . $d['preview'] . "\n\nHello,\n\n" . $d['intro'] . "\n\n" . $d['phone'] . "\n\nSee what your website could look like:\n{{approved_industry_matching_invitation_url}}\n\nShort commercial: $commercial\n\nThe eligible focused starter is \$199 upfront, including the first year of managed hosting.\n\n$terms\n\nThe eventual sample is illustrative; connected workflow is agreed in scope. No approved matching sample exists for this draft yet.\n\nShay-Shay\nFAMtastic Designs assistant\nDigital card: $card\nQR fallback: $card\nUnsubscribe: {{approved_unsubscribe_url}}\nFAMtastic Designs, 1729 NW St. Lucie West Blvd #1181, Port Saint Lucie, FL 34986\n\nDRAFT ONLY — owner approval, matching preview, native bindings and sender/recipient guards pending.\n";
  $stepsText="Your next steps are simple:\n1. Create your free account and complete your website interview.\n2. Review three design directions, choose your favorite and request any adjustments.\n3. Review your staged website.\n4. Pay $199 and approve launch—we connect your domain and get your website online.\n\nCreate your free account: {{native_sample_continuation_registration_url}}\n\nWe aim for same-day launch once your site is approved, payment is complete and the domain is ready.\nDomain and email setup options are agreed in scope. Mailbox subscriptions are separate.\n\n";
  $text=str_replace($terms,$stepsText . $terms,$text);
  $drafts[count($drafts)-1]['copy_revision']=2;
  $drafts[count($drafts)-1]['copy_review']='owner_authorized_next_steps_revision';
  $drafts[count($drafts)-1]['registration_binding']='https://famtasticdesigns.com/login?mode=register&sample_continuation=<opaque_invitation_token>';
  file_put_contents($out . '/' . $d['id'] . '.txt',$text);
}
$manifest=['schema'=>'famtastic.acquisition-industry-d0-drafts.v1','created_at'=>gmdate(DATE_ATOM),'status'=>'nine_draft_content_variants_not_owner_approved','approved_beauty_source'=>'docs/research/acquisition-199/CREATIVE-APPROVAL.json','approved_beauty_unchanged'=>true,'shared_layout'=>'BrandedEmail + approved beauty early CTA/commercial/terms/signature/card/QR pattern','industry_count'=>9,'complete_matching_previews'=>0,'new_paid_generation_calls'=>0,'new_external_provider_calls'=>0,'cost_limit'=>'No provider spend; session subscription/ideation cost unmeasured','followups'=>'D3/D7 unapproved, not generated or scheduled','source_asset_audit'=>['confirmed_owned_campaign_scene'=>'booked-and-branded-pilot: agency-owned fictional barber/beauty imagery, inappropriate for these other segments','other_owned_assets'=>'marketing/creative/plates, anchors and cost-is-not-the-reason broll: generic office/shop/phone or salon concept scenes; no matching category proof','customer_reference_boundary'=>'Existing customer lawn/DJ/shoe/P.I.T. layouts are references only. Customer media has no cleared cross-customer campaign reuse.','initial_six'=>'Rejected; no reuse as new preview fallback'],'drafts'=>$drafts];
file_put_contents($out . '/drafts.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR) . "\n");
$css='*{box-sizing:border-box}body{margin:0;background:#070907;color:#f6f8f1;font:16px/1.65 system-ui}header,main,footer{max-width:1100px;margin:auto;padding:30px 6%}h1{font-size:clamp(34px,6vw,58px);line-height:1.1}h2{font-size:24px}a{color:#7cfc00;display:inline-flex;min-height:44px;align-items:center;text-underline-offset:4px}a:focus-visible{outline:3px solid #7cfc00;outline-offset:4px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{padding:22px;background:#141914;border:1px solid #374333;border-radius:6px}.tag{font-size:12px;color:#d4e4b8}.links{display:flex;gap:20px;flex-wrap:wrap}.note{border-left:3px solid #7cfc00;padding:14px;font-size:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}header,main,footer{padding:24px 6%}}';
$head='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><style>' . $css . '</style>';
$gallery=$head . '<title>Remaining industry D0 drafts</title></head><body><header><p class="tag">Nine remaining industry variants · draft only</p><h1>Matched words.<br>Matching previews still needed.</h1><p>The approved beauty layout is reused for these content drafts. No beauty photo or rejected sample substitutes for a different industry.</p><p class="note">Nine complete copy drafts; zero approved matching destinations. This is an owner review gallery, not a ready-to-send campaign.</p></header><main><div class="grid">';
$status=$head . '<title>Industry preview status — drafts</title></head><body><header><p class="tag">Review status · no finished matching preview yet</p><h1>The next image must belong to the offer.</h1><p>These drafts need matching cleared imagery, an appropriate destination and exact owner approval. They cannot route another industry to the approved beauty sample.</p></header><main>';
foreach($drafts as $m){
 $id=explode('-d0-v1',$m['id'])[0];
 $gallery.='<article class="card"><p class="tag">D0 draft · approval and matching preview pending</p><h2>' . $esc($m['industry_source_label']) . '</h2><p><strong>' . $esc($m['subject']) . '</strong></p><p>' . $esc($m['preview']) . '</p><div class="links"><a href="' . $id . '.html">Read HTML draft</a><a href="' . $id . '.txt">Read plain text</a><a href="' . $id . '-images-blocked.html">Images blocked</a></div></article>';
 $status.='<section class="card" id="' . $id . '"><p class="tag">Missing owned matching asset · destination unapproved</p><h2>' . $esc($m['industry_source_label']) . '</h2><p>' . $esc($m['matching_preview']['brief']) . '</p><p class="note">' . $esc($m['matching_preview']['scope_boundary']) . '</p><a href="' . $id . '.html">Return to the content draft</a></section>';
}
$gallery.='</div><p><a href="preview-status.html">Review all missing preview requirements</a></p></main><footer>Draft source only · no provider, schedule, SMTP or deployment</footer></body></html>';
$status.='</main><footer><a href="index.html">Back to the nine drafts</a></footer></body></html>';
file_put_contents($out . '/index.html',$gallery);
file_put_contents($out . '/preview-status.html',$status);
$freeze();
if(in_array('--test',$argv,true)){
 $assertions=0;
 $check=static function(bool $ok,string $why) use (&$assertions):void {if(!$ok) throw new RuntimeException($why);$assertions++;};
 $check(count($drafts)===9,'Nine remaining industry D0s');
 $check(count(array_unique(array_column($drafts,'subject')))===9,'Distinct industry subjects');
 $check(!in_array($coverage['categories'][0]['label'],array_column($drafts,'industry_source_label'),true),'Approved beauty variant excluded from mutation');
 foreach($drafts as $i=>$m){
  $id=explode('-d0-v1',$m['id'])[0];$html=file_get_contents($out . '/' . $id . '.html');$text=file_get_contents($out . '/' . $id . '.txt');
  $check($m['industry_source_label']===$coverage['categories'][$i+1]['label'],'Exact supplied broad industry label');
  $check(str_contains($html,'data-famtastic-email-brand="v1"'),'Existing branded shell');
  $check(substr_count($html,'class="primary-demo-cta"')===1 && strpos($html,'class="primary-demo-cta"')<strpos($html,'$199 upfront'),'Early unique primary CTA');
  $check(str_contains($html,$commercial) && str_contains($html,$card) && str_contains($html,'connect-qr.png'),'Canonical commercial/card/QR');
  $check(str_contains($html,'Shay-Shay') && str_contains($html,'FAMtastic Designs assistant'),'Disclosed approved assistant identity');
  $check($m['greeting']==='Hello,' && !preg_match('/Juniper|Hello, [A-Z]|lost revenue|guaranteed bookings|48 hours/',$html),'No invented identity/result/turnaround');
  $check(!preg_match('/hair-studio|beauty-lab|beauty-template|-preview\.jpg/',$html),'No industry mismatch fallback');
  $check($m['matching_preview']['image_path']===null && !$m['matching_preview']['owner_approved'] && !$m['send_policy']['approved'],'Missing preview and approval remain explicit');
  $check(str_contains($text,'$9.99/month only with separate recurring authorization') && str_contains($text,'domain renewal is separate'),'Actual renewal terms');
  $check(str_contains($html,'preview-status.html#' . $id) && str_contains($status,'id="' . $id . '"'),'Review CTA resolves actual status section');
  $check(str_contains($text,'{{approved_industry_matching_invitation_url}}') && !$m['send_policy']['dispatch_connected'],'No issued invitation or dispatch');
  $check(strlen($html)<100000 && !str_contains($html,'data:image'),'Compact shared assets');
  $check(!preg_match('/<img\b/',file_get_contents($out . '/' . $id . '-images-blocked.html')),'Image-blocked fallback retains copy');
  $check($m['followups']['d3']==='unapproved_not_generated' && $m['followups']['d7']==='unapproved_not_generated','No unapproved followup generation');
 }
 $freeze();$check(true,'All approved beauty hash bindings unchanged');
 file_put_contents($out . '/source-qa.json',json_encode(['schema'=>'famtastic.industry-d0-source-qa.v1','tested_at'=>gmdate(DATE_ATOM),'assertions'=>$assertions,'passed'=>true,'approved_beauty_unchanged'=>true,'matching_previews_approved'=>0,'limitations'=>['Source/render integrity only','New variants not owner approved','Missing matched assets and destinations','No new inbox/mobile/browser/provider proof']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR) . "\n");
 echo 'PASS ' . $assertions . " industry draft integrity checks; approved beauty bytes unchanged.\n";
}
echo "Saved nine D0 content drafts: marketing/campaigns/acquisition-199/industry-d0-drafts/index.html. Zero matching previews approved; no sending.\n";
